2000 8 128 
993 hzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagw
533 fjuhfagwfjuhfagwhzhiaytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagw
703 wfjdkfjnfjuhfaawhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagw
839 hfkjdhasfjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagw
1500 fhduuhnbfjuhfaaazhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagw
1356 fhuitaaaajuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagw
530 faaauhnbfjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagw
535 faaauhnbfjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfaaahzhahytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagwhzhihytufjuhfagw


